#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Nutrition")]
	public partial class DbClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFoodGroup(FoodGroup instance);
    partial void UpdateFoodGroup(FoodGroup instance);
    partial void DeleteFoodGroup(FoodGroup instance);
    partial void InsertFood(Food instance);
    partial void UpdateFood(Food instance);
    partial void DeleteFood(Food instance);
    partial void InsertWeight(Weight instance);
    partial void UpdateWeight(Weight instance);
    partial void DeleteWeight(Weight instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertHistory(History instance);
    partial void UpdateHistory(History instance);
    partial void DeleteHistory(History instance);
    partial void InsertProfile(Profile instance);
    partial void UpdateProfile(Profile instance);
    partial void DeleteProfile(Profile instance);
    #endregion
		
		public DbClassesDataContext() : 
				base(global::Repositories.Properties.Settings.Default.NutritionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FoodGroup> FoodGroups
		{
			get
			{
				return this.GetTable<FoodGroup>();
			}
		}
		
		public System.Data.Linq.Table<Food> Foods
		{
			get
			{
				return this.GetTable<Food>();
			}
		}
		
		public System.Data.Linq.Table<Weight> Weights
		{
			get
			{
				return this.GetTable<Weight>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<History> Histories
		{
			get
			{
				return this.GetTable<History>();
			}
		}
		
		public System.Data.Linq.Table<Profile> Profiles
		{
			get
			{
				return this.GetTable<Profile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USDA_FD_GROUP")]
	public partial class FoodGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _FdGrp_Cd;
		
		private string _FdGrp_Desc;
		
		private EntitySet<Food> _USDA_FOOD_DEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnFdGrp_DescChanging(string value);
    partial void OnFdGrp_DescChanged();
    #endregion
		
		public FoodGroup()
		{
			this._USDA_FOOD_DEs = new EntitySet<Food>(new Action<Food>(this.attach_USDA_FOOD_DEs), new Action<Food>(this.detach_USDA_FOOD_DEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FdGrp_Cd", Storage="_FdGrp_Cd", DbType="Decimal(4,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Id
		{
			get
			{
				return this._FdGrp_Cd;
			}
			set
			{
				if ((this._FdGrp_Cd != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._FdGrp_Cd = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FdGrp_Desc", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string FdGrp_Desc
		{
			get
			{
				return this._FdGrp_Desc;
			}
			set
			{
				if ((this._FdGrp_Desc != value))
				{
					this.OnFdGrp_DescChanging(value);
					this.SendPropertyChanging();
					this._FdGrp_Desc = value;
					this.SendPropertyChanged("FdGrp_Desc");
					this.OnFdGrp_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodGroup_Food", Storage="_USDA_FOOD_DEs", ThisKey="Id", OtherKey="FdGrp_Cd")]
		internal EntitySet<Food> Foods
		{
			get
			{
				return this._USDA_FOOD_DEs;
			}
			set
			{
				this._USDA_FOOD_DEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USDA_FOOD_DEs(Food entity)
		{
			this.SendPropertyChanging();
			entity.FoodGroup = this;
		}
		
		private void detach_USDA_FOOD_DEs(Food entity)
		{
			this.SendPropertyChanging();
			entity.FoodGroup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USDA_FOOD_DES")]
	public partial class Food : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _NDB_No;
		
		private decimal _FdGrp_Cd;
		
		private string _Long_Desc;
		
		private string _Shrt_Desc;
		
		private System.Nullable<decimal> _Refuse;
		
		private System.Nullable<decimal> _N_Factor;
		
		private System.Nullable<decimal> _Pro_Factor;
		
		private System.Nullable<decimal> _Fat_Factor;
		
		private System.Nullable<decimal> _CHO_Factor;
		
		private EntitySet<Weight> _USDA_WEIGHTs;
		
		private EntitySet<History> _Histories;
		
		private EntityRef<FoodGroup> _USDA_FD_GROUP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnFdGrp_CdChanging(decimal value);
    partial void OnFdGrp_CdChanged();
    partial void OnLong_DescChanging(string value);
    partial void OnLong_DescChanged();
    partial void OnShrt_DescChanging(string value);
    partial void OnShrt_DescChanged();
    partial void OnRefuseChanging(System.Nullable<decimal> value);
    partial void OnRefuseChanged();
    partial void OnN_FactorChanging(System.Nullable<decimal> value);
    partial void OnN_FactorChanged();
    partial void OnPro_FactorChanging(System.Nullable<decimal> value);
    partial void OnPro_FactorChanged();
    partial void OnFat_FactorChanging(System.Nullable<decimal> value);
    partial void OnFat_FactorChanged();
    partial void OnCHO_FactorChanging(System.Nullable<decimal> value);
    partial void OnCHO_FactorChanged();
    #endregion
		
		public Food()
		{
			this._USDA_WEIGHTs = new EntitySet<Weight>(new Action<Weight>(this.attach_USDA_WEIGHTs), new Action<Weight>(this.detach_USDA_WEIGHTs));
			this._Histories = new EntitySet<History>(new Action<History>(this.attach_Histories), new Action<History>(this.detach_Histories));
			this._USDA_FD_GROUP = default(EntityRef<FoodGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NDB_No", Storage="_NDB_No", DbType="Decimal(5,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Id
		{
			get
			{
				return this._NDB_No;
			}
			set
			{
				if ((this._NDB_No != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._NDB_No = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FdGrp_Cd", DbType="Decimal(4,0) NOT NULL")]
		public decimal FdGrp_Cd
		{
			get
			{
				return this._FdGrp_Cd;
			}
			set
			{
				if ((this._FdGrp_Cd != value))
				{
					if (this._USDA_FD_GROUP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFdGrp_CdChanging(value);
					this.SendPropertyChanging();
					this._FdGrp_Cd = value;
					this.SendPropertyChanged("FdGrp_Cd");
					this.OnFdGrp_CdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long_Desc", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Long_Desc
		{
			get
			{
				return this._Long_Desc;
			}
			set
			{
				if ((this._Long_Desc != value))
				{
					this.OnLong_DescChanging(value);
					this.SendPropertyChanging();
					this._Long_Desc = value;
					this.SendPropertyChanged("Long_Desc");
					this.OnLong_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shrt_Desc", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Shrt_Desc
		{
			get
			{
				return this._Shrt_Desc;
			}
			set
			{
				if ((this._Shrt_Desc != value))
				{
					this.OnShrt_DescChanging(value);
					this.SendPropertyChanging();
					this._Shrt_Desc = value;
					this.SendPropertyChanged("Shrt_Desc");
					this.OnShrt_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Refuse", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> Refuse
		{
			get
			{
				return this._Refuse;
			}
			set
			{
				if ((this._Refuse != value))
				{
					this.OnRefuseChanging(value);
					this.SendPropertyChanging();
					this._Refuse = value;
					this.SendPropertyChanged("Refuse");
					this.OnRefuseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Factor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> N_Factor
		{
			get
			{
				return this._N_Factor;
			}
			set
			{
				if ((this._N_Factor != value))
				{
					this.OnN_FactorChanging(value);
					this.SendPropertyChanging();
					this._N_Factor = value;
					this.SendPropertyChanged("N_Factor");
					this.OnN_FactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Factor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Pro_Factor
		{
			get
			{
				return this._Pro_Factor;
			}
			set
			{
				if ((this._Pro_Factor != value))
				{
					this.OnPro_FactorChanging(value);
					this.SendPropertyChanging();
					this._Pro_Factor = value;
					this.SendPropertyChanged("Pro_Factor");
					this.OnPro_FactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat_Factor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Fat_Factor
		{
			get
			{
				return this._Fat_Factor;
			}
			set
			{
				if ((this._Fat_Factor != value))
				{
					this.OnFat_FactorChanging(value);
					this.SendPropertyChanging();
					this._Fat_Factor = value;
					this.SendPropertyChanged("Fat_Factor");
					this.OnFat_FactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHO_Factor", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> CHO_Factor
		{
			get
			{
				return this._CHO_Factor;
			}
			set
			{
				if ((this._CHO_Factor != value))
				{
					this.OnCHO_FactorChanging(value);
					this.SendPropertyChanging();
					this._CHO_Factor = value;
					this.SendPropertyChanged("CHO_Factor");
					this.OnCHO_FactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_Weight", Storage="_USDA_WEIGHTs", ThisKey="Id", OtherKey="Id")]
		internal EntitySet<Weight> Weights
		{
			get
			{
				return this._USDA_WEIGHTs;
			}
			set
			{
				this._USDA_WEIGHTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_History", Storage="_Histories", ThisKey="Id", OtherKey="NDB_No")]
		internal EntitySet<History> Histories
		{
			get
			{
				return this._Histories;
			}
			set
			{
				this._Histories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodGroup_Food", Storage="_USDA_FD_GROUP", ThisKey="FdGrp_Cd", OtherKey="Id", IsForeignKey=true)]
		public FoodGroup FoodGroup
		{
			get
			{
				return this._USDA_FD_GROUP.Entity;
			}
			set
			{
				FoodGroup previousValue = this._USDA_FD_GROUP.Entity;
				if (((previousValue != value) 
							|| (this._USDA_FD_GROUP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USDA_FD_GROUP.Entity = null;
						previousValue.Foods.Remove(this);
					}
					this._USDA_FD_GROUP.Entity = value;
					if ((value != null))
					{
						value.Foods.Add(this);
						this._FdGrp_Cd = value.Id;
					}
					else
					{
						this._FdGrp_Cd = default(decimal);
					}
					this.SendPropertyChanged("FoodGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USDA_WEIGHTs(Weight entity)
		{
			this.SendPropertyChanging();
			entity.Food = this;
		}
		
		private void detach_USDA_WEIGHTs(Weight entity)
		{
			this.SendPropertyChanging();
			entity.Food = null;
		}
		
		private void attach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.Food = this;
		}
		
		private void detach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.Food = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USDA_WEIGHT")]
	public partial class Weight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _NDB_No;
		
		private decimal _Seq;
		
		private decimal _Amount;
		
		private string _Msre_Desc;
		
		private decimal _Gm_Wgt;
		
		private EntityRef<Food> _USDA_FOOD_DE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnSeqChanging(decimal value);
    partial void OnSeqChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnMsre_DescChanging(string value);
    partial void OnMsre_DescChanged();
    partial void OnGm_WgtChanging(decimal value);
    partial void OnGm_WgtChanged();
    #endregion
		
		public Weight()
		{
			this._USDA_FOOD_DE = default(EntityRef<Food>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NDB_No", Storage="_NDB_No", DbType="Decimal(5,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Id
		{
			get
			{
				return this._NDB_No;
			}
			set
			{
				if ((this._NDB_No != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._NDB_No = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seq", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Seq
		{
			get
			{
				return this._Seq;
			}
			set
			{
				if ((this._Seq != value))
				{
					this.OnSeqChanging(value);
					this.SendPropertyChanging();
					this._Seq = value;
					this.SendPropertyChanged("Seq");
					this.OnSeqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(5,3) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msre_Desc", DbType="NVarChar(84) NOT NULL", CanBeNull=false)]
		public string Msre_Desc
		{
			get
			{
				return this._Msre_Desc;
			}
			set
			{
				if ((this._Msre_Desc != value))
				{
					this.OnMsre_DescChanging(value);
					this.SendPropertyChanging();
					this._Msre_Desc = value;
					this.SendPropertyChanged("Msre_Desc");
					this.OnMsre_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gm_Wgt", DbType="Decimal(7,1) NOT NULL")]
		public decimal Gm_Wgt
		{
			get
			{
				return this._Gm_Wgt;
			}
			set
			{
				if ((this._Gm_Wgt != value))
				{
					this.OnGm_WgtChanging(value);
					this.SendPropertyChanging();
					this._Gm_Wgt = value;
					this.SendPropertyChanged("Gm_Wgt");
					this.OnGm_WgtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_Weight", Storage="_USDA_FOOD_DE", ThisKey="Id", OtherKey="Id", IsForeignKey=true)]
		public Food Food
		{
			get
			{
				return this._USDA_FOOD_DE.Entity;
			}
			set
			{
				Food previousValue = this._USDA_FOOD_DE.Entity;
				if (((previousValue != value) 
							|| (this._USDA_FOOD_DE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USDA_FOOD_DE.Entity = null;
						previousValue.Weights.Remove(this);
					}
					this._USDA_FOOD_DE.Entity = value;
					if ((value != null))
					{
						value.Weights.Add(this);
						this._NDB_No = value.Id;
					}
					else
					{
						this._NDB_No = default(decimal);
					}
					this.SendPropertyChanged("Food");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NUT_USER")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _USER_No;
		
		private string _FirstName;
		
		private string _LastName;
		
		private EntitySet<History> _Histories;
		
		private EntitySet<Profile> _Profiles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    #endregion
		
		public User()
		{
			this._Histories = new EntitySet<History>(new Action<History>(this.attach_Histories), new Action<History>(this.detach_Histories));
			this._Profiles = new EntitySet<Profile>(new Action<Profile>(this.attach_Profiles), new Action<Profile>(this.detach_Profiles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USER_No", Storage="_USER_No", AutoSync=AutoSync.OnInsert, DbType="Decimal(5,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._USER_No;
			}
			set
			{
				if ((this._USER_No != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._USER_No = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(160) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(160) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_History", Storage="_Histories", ThisKey="Id", OtherKey="USER_No")]
		internal EntitySet<History> Histories
		{
			get
			{
				return this._Histories;
			}
			set
			{
				this._Histories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_NUT_PROFILE", Storage="_Profiles", ThisKey="Id", OtherKey="USER_No")]
		internal EntitySet<Profile> Profiles
		{
			get
			{
				return this._Profiles;
			}
			set
			{
				this._Profiles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Histories(History entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Profiles(Profile entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Profiles(Profile entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NUT_HISTORY")]
	public partial class History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id;
		
		private decimal _USER_No;
		
		private decimal _NDB_No;
		
		private decimal _Seq;
		
		private decimal _Food_Amount;
		
		private decimal _Meal_Calorie;
		
		private string _Meal_Time;
		
		private string _Add_Date;
		
		private EntityRef<Food> _Food;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnUSER_NoChanging(decimal value);
    partial void OnUSER_NoChanged();
    partial void OnNDB_NoChanging(decimal value);
    partial void OnNDB_NoChanged();
    partial void OnSeqChanging(decimal value);
    partial void OnSeqChanged();
    partial void OnFood_AmountChanging(decimal value);
    partial void OnFood_AmountChanged();
    partial void OnMeal_CalorieChanging(decimal value);
    partial void OnMeal_CalorieChanged();
    partial void OnMeal_TimeChanging(string value);
    partial void OnMeal_TimeChanged();
    partial void OnAdd_DateChanging(string value);
    partial void OnAdd_DateChanged();
    #endregion
		
		public History()
		{
			this._Food = default(EntityRef<Food>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(5,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_No", DbType="Decimal(5,0) NOT NULL")]
		public decimal USER_No
		{
			get
			{
				return this._USER_No;
			}
			set
			{
				if ((this._USER_No != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSER_NoChanging(value);
					this.SendPropertyChanging();
					this._USER_No = value;
					this.SendPropertyChanged("USER_No");
					this.OnUSER_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NDB_No", DbType="Decimal(5,0) NOT NULL")]
		public decimal NDB_No
		{
			get
			{
				return this._NDB_No;
			}
			set
			{
				if ((this._NDB_No != value))
				{
					if (this._Food.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNDB_NoChanging(value);
					this.SendPropertyChanging();
					this._NDB_No = value;
					this.SendPropertyChanged("NDB_No");
					this.OnNDB_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seq", DbType="Decimal(2,0) NOT NULL")]
		public decimal Seq
		{
			get
			{
				return this._Seq;
			}
			set
			{
				if ((this._Seq != value))
				{
					this.OnSeqChanging(value);
					this.SendPropertyChanging();
					this._Seq = value;
					this.SendPropertyChanged("Seq");
					this.OnSeqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Amount", DbType="Decimal(16,14) NOT NULL")]
		public decimal Food_Amount
		{
			get
			{
				return this._Food_Amount;
			}
			set
			{
				if ((this._Food_Amount != value))
				{
					this.OnFood_AmountChanging(value);
					this.SendPropertyChanging();
					this._Food_Amount = value;
					this.SendPropertyChanged("Food_Amount");
					this.OnFood_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meal_Calorie", DbType="Decimal(10,0) NOT NULL")]
		public decimal Meal_Calorie
		{
			get
			{
				return this._Meal_Calorie;
			}
			set
			{
				if ((this._Meal_Calorie != value))
				{
					this.OnMeal_CalorieChanging(value);
					this.SendPropertyChanging();
					this._Meal_Calorie = value;
					this.SendPropertyChanged("Meal_Calorie");
					this.OnMeal_CalorieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meal_Time", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Meal_Time
		{
			get
			{
				return this._Meal_Time;
			}
			set
			{
				if ((this._Meal_Time != value))
				{
					this.OnMeal_TimeChanging(value);
					this.SendPropertyChanging();
					this._Meal_Time = value;
					this.SendPropertyChanged("Meal_Time");
					this.OnMeal_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_Date", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Add_Date
		{
			get
			{
				return this._Add_Date;
			}
			set
			{
				if ((this._Add_Date != value))
				{
					this.OnAdd_DateChanging(value);
					this.SendPropertyChanging();
					this._Add_Date = value;
					this.SendPropertyChanged("Add_Date");
					this.OnAdd_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Food_History", Storage="_Food", ThisKey="NDB_No", OtherKey="Id", IsForeignKey=true)]
		public Food Food
		{
			get
			{
				return this._Food.Entity;
			}
			set
			{
				Food previousValue = this._Food.Entity;
				if (((previousValue != value) 
							|| (this._Food.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Food.Entity = null;
						previousValue.Histories.Remove(this);
					}
					this._Food.Entity = value;
					if ((value != null))
					{
						value.Histories.Add(this);
						this._NDB_No = value.Id;
					}
					else
					{
						this._NDB_No = default(decimal);
					}
					this.SendPropertyChanged("Food");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_History", Storage="_User", ThisKey="USER_No", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Histories.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Histories.Add(this);
						this._USER_No = value.Id;
					}
					else
					{
						this._USER_No = default(decimal);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NUT_PROFILE")]
	public partial class Profile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id;
		
		private decimal _USER_No;
		
		private string _Gender;
		
		private decimal _Height;
		
		private string _HeightUnit;
		
		private decimal _Weight;
		
		private string _WeightUnit;
		
		private decimal _Age;
		
		private decimal _Calc_Calorie;
		
		private decimal _Expc_Calorie;
		
		private decimal _BMR;
		
		private decimal _BMI;
		
		private decimal _Activity;
		
		private string _Add_Date;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnUSER_NoChanging(decimal value);
    partial void OnUSER_NoChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnHeightChanging(decimal value);
    partial void OnHeightChanged();
    partial void OnHeightUnitChanging(string value);
    partial void OnHeightUnitChanged();
    partial void OnWeightChanging(decimal value);
    partial void OnWeightChanged();
    partial void OnWeightUnitChanging(string value);
    partial void OnWeightUnitChanged();
    partial void OnAgeChanging(decimal value);
    partial void OnAgeChanged();
    partial void OnCalc_CalorieChanging(decimal value);
    partial void OnCalc_CalorieChanged();
    partial void OnExpc_CalorieChanging(decimal value);
    partial void OnExpc_CalorieChanged();
    partial void OnBMRChanging(decimal value);
    partial void OnBMRChanged();
    partial void OnBMIChanging(decimal value);
    partial void OnBMIChanged();
    partial void OnActivityChanging(decimal value);
    partial void OnActivityChanged();
    partial void OnAdd_DateChanging(string value);
    partial void OnAdd_DateChanged();
    #endregion
		
		public Profile()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(5,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_No", DbType="Decimal(5,0) NOT NULL")]
		public decimal USER_No
		{
			get
			{
				return this._USER_No;
			}
			set
			{
				if ((this._USER_No != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSER_NoChanging(value);
					this.SendPropertyChanging();
					this._USER_No = value;
					this.SendPropertyChanged("USER_No");
					this.OnUSER_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Decimal(10,2) NOT NULL")]
		public decimal Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeightUnit", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string HeightUnit
		{
			get
			{
				return this._HeightUnit;
			}
			set
			{
				if ((this._HeightUnit != value))
				{
					this.OnHeightUnitChanging(value);
					this.SendPropertyChanging();
					this._HeightUnit = value;
					this.SendPropertyChanged("HeightUnit");
					this.OnHeightUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(10,2) NOT NULL")]
		public decimal Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightUnit", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string WeightUnit
		{
			get
			{
				return this._WeightUnit;
			}
			set
			{
				if ((this._WeightUnit != value))
				{
					this.OnWeightUnitChanging(value);
					this.SendPropertyChanging();
					this._WeightUnit = value;
					this.SendPropertyChanged("WeightUnit");
					this.OnWeightUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Decimal(4,0) NOT NULL")]
		public decimal Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calc_Calorie", DbType="Decimal(10,2) NOT NULL")]
		public decimal Calc_Calorie
		{
			get
			{
				return this._Calc_Calorie;
			}
			set
			{
				if ((this._Calc_Calorie != value))
				{
					this.OnCalc_CalorieChanging(value);
					this.SendPropertyChanging();
					this._Calc_Calorie = value;
					this.SendPropertyChanged("Calc_Calorie");
					this.OnCalc_CalorieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expc_Calorie", DbType="Decimal(10,2) NOT NULL")]
		public decimal Expc_Calorie
		{
			get
			{
				return this._Expc_Calorie;
			}
			set
			{
				if ((this._Expc_Calorie != value))
				{
					this.OnExpc_CalorieChanging(value);
					this.SendPropertyChanging();
					this._Expc_Calorie = value;
					this.SendPropertyChanged("Expc_Calorie");
					this.OnExpc_CalorieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR", DbType="Decimal(10,2) NOT NULL")]
		public decimal BMR
		{
			get
			{
				return this._BMR;
			}
			set
			{
				if ((this._BMR != value))
				{
					this.OnBMRChanging(value);
					this.SendPropertyChanging();
					this._BMR = value;
					this.SendPropertyChanged("BMR");
					this.OnBMRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Decimal(10,2) NOT NULL")]
		public decimal BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity", DbType="Decimal(4,2) NOT NULL")]
		public decimal Activity
		{
			get
			{
				return this._Activity;
			}
			set
			{
				if ((this._Activity != value))
				{
					this.OnActivityChanging(value);
					this.SendPropertyChanging();
					this._Activity = value;
					this.SendPropertyChanged("Activity");
					this.OnActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_Date", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Add_Date
		{
			get
			{
				return this._Add_Date;
			}
			set
			{
				if ((this._Add_Date != value))
				{
					this.OnAdd_DateChanging(value);
					this.SendPropertyChanging();
					this._Add_Date = value;
					this.SendPropertyChanged("Add_Date");
					this.OnAdd_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_NUT_PROFILE", Storage="_User", ThisKey="USER_No", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Profiles.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Profiles.Add(this);
						this._USER_No = value.Id;
					}
					else
					{
						this._USER_No = default(decimal);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
